In [1]:
import pandas as pd

In [2]:
data1 = pd.read_csv('soccer.csv', sep = ',', header = 0, engine = 'python')
data2 = pd.read_csv('soccer2.csv', sep = ',', header = 0, engine = 'python')
data3 = pd.read_csv('soccer3.csv', sep = ',', header = 0, engine = 'python')

In [3]:
# csv 파일 병합
total_data = pd.concat([data1, data2, data3])
total_data

,Match_date,teamName,homeAway,Ball Possession,Goal Attempts,Shots On,Shots Off,Blocked Shots,Free kick,Offsides,...,Substitute,Substitute 1st Half,Substitute 2nd Half,Throw Ins 1st Half,Throw Ins 2nd Half,Treatment 1st Half,Treatment 2nd Half,Yellow Cards 1st Half,Yellow Cards 2nd Half,Result
0,Match date: 05-08-2022 / 22:00,CRYSTAL PALACE,1,56,10,2,2,6,13,1,...,4,0,4,12,10,0,1,0,1.0,L
1,Match date: 05-08-2022 / 22:00,ARSENAL,2,44,11,2,4,5,17,2,...,3,0,3,12,1,0,0,1,1.0,W
2,Match date: 06-08-2022 / 14:30,FULHAM,1,33,9,3,2,4,13,4,...,3,0,3,8,13,0,0,1,NaN,D
3,Match date: 06-08-2022 / 14:30,LIVERPOOL,2,67,11,3,5,3,11,4,...,4,0,4,14,20,1,1,0,NaN,D
4,Match date: 06-08-2022 / 17:00,TOTTENHAM,1,57,18,8,5,5,6,2,...,5,0,5,12,6,0,0,1,2.0,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,Match date: 06-05-2023 / 17:00,ASTON VILLA,2,62,17,3,6,8,23,2,...,5,0,5,14,6,1,3,1,2.0,L
164,Match date: 06-05-2023 / 17:00,TOTTENHAM,1,57,8,3,3,2,14,1,...,3,0,3,5,7,0,2,0,3.0,W
165,Match date: 06-05-2023 / 17:00,CRYSTAL PALACE,2,43,7,2,3,2,16,0,...,2,0,2,7,20,0,0,0,5.0,L
166,Match date: 06-05-2023 / 17:00,MANCHESTER CITY,1,81,18,6,10,2,19,4,...,3,0,3,5,7,0,1,0,0.0,W
167,Match date: 06-05-2023 / 17:00,LEEDS,2,19,4,2,1,1,7,3,...,5,0,5,4,6,0,0,1,2.0,L

In [4]:
total_data.columns = total_data.columns.str.replace(' ', '_')
total_data.columns

Index(['Match_date', 'teamName', 'homeAway', 'Ball_Possession',
       'Goal_Attempts', 'Shots_On', 'Shots_Off', 'Blocked_Shots', 'Free_kick',
       'Offsides', 'Throw_Ins', 'Saves', 'Fouls_Commited', 'Red_Cards',
       'Yellow_Cards', 'Assists_1st_Half', 'Assists_2nd_Half',
       'Ball_Possession_1st_Half', 'Ball_Possession_2nd_Half',
       'Blockes_Shots_1st_Half', 'Blockes_Shots_2nd_Half', 'Corners',
       'Corners_1st_Half', 'Corners_2nd_Half', 'Counter_Attacks',
       'Counter_Attacks_1st_Half', 'Counter_Attacks_2nd_Half', 'Crosses',
       'Crosses_1st_Half', 'Crosses_2nd_Half', 'Fouls_Commited_1st_Half',
       'Fouls_Commited_2nd_Half', 'Free_kick_1st_Half', 'Free_kick_2nd_Half',
       'Goal_Attempts_1st_Half', 'Goal_Attempts_2nd_Half', 'Goal_Kick',
       'Goal_Kick_1st_Half', 'Goal_Kick_2nd_Half', 'Goals_1st_Half',
       'Goals_2nd_Half', 'Offsides_1st_Half', 'Offsides_2nd_Half',
       'Red_Cards_1st_Half', 'Red_Cards_2nd_Half', 'Saves_1st_Half',
       'Saves_2nd_Half', 'Shots_Off_1st_Half', 'Shots_Off_2nd_Half',
       'Shots_On_1st_Half', 'Shots_On_2nd_Half', 'Substitute',
       'Substitute_1st_Half', 'Substitute_2nd_Half', 'Throw_Ins_1st_Half',
       'Throw_Ins_2nd_Half', 'Treatment_1st_Half', 'Treatment_2nd_Half',
       'Yellow_Cards_1st_Half', 'Yellow_Cards_2nd_Half', 'Result'],
      dtype='object')

In [5]:
# 전반전 슈팅값 변수 추가
total_data['Shots_1st_Half'] = total_data['Shots_Off_1st_Half'] + total_data['Shots_On_1st_Half']

In [6]:
# homeAway에서 home은 1, Away는 0으로 설정
total_data = total_data.replace({'homeAway': 2}, 0)
total_data

,Match_date,teamName,homeAway,Ball_Possession,Goal_Attempts,Shots_On,Shots_Off,Blocked_Shots,Free_kick,Offsides,...,Substitute_1st_Half,Substitute_2nd_Half,Throw_Ins_1st_Half,Throw_Ins_2nd_Half,Treatment_1st_Half,Treatment_2nd_Half,Yellow_Cards_1st_Half,Yellow_Cards_2nd_Half,Result,Shots_1st_Half
0,Match date: 05-08-2022 / 22:00,CRYSTAL PALACE,1,56,10,2,2,6,13,1,...,0,4,12,10,0,1,0,1.0,L,1
1,Match date: 05-08-2022 / 22:00,ARSENAL,0,44,11,2,4,5,17,2,...,0,3,12,1,0,0,1,1.0,W,3
2,Match date: 06-08-2022 / 14:30,FULHAM,1,33,9,3,2,4,13,4,...,0,3,8,13,0,0,1,NaN,D,2
3,Match date: 06-08-2022 / 14:30,LIVERPOOL,0,67,11,3,5,3,11,4,...,0,4,14,20,1,1,0,NaN,D,2
4,Match date: 06-08-2022 / 17:00,TOTTENHAM,1,57,18,8,5,5,6,2,...,0,5,12,6,0,0,1,2.0,W,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,Match date: 06-05-2023 / 17:00,ASTON VILLA,0,62,17,3,6,8,23,2,...,0,5,14,6,1,3,1,2.0,L,4
164,Match date: 06-05-2023 / 17:00,TOTTENHAM,1,57,8,3,3,2,14,1,...,0,3,5,7,0,2,0,3.0,W,3
165,Match date: 06-05-2023 / 17:00,CRYSTAL PALACE,0,43,7,2,3,2,16,0,...,0,2,7,20,0,0,0,5.0,L,2
166,Match date: 06-05-2023 / 17:00,MANCHESTER CITY,1,81,18,6,10,2,19,4,...,0,3,5,7,0,1,0,0.0,W,10
167,Match date: 06-05-2023 / 17:00,LEEDS,0,19,4,2,1,1,7,3,...,0,5,4,6,0,0,1,2.0,L,2

In [7]:
# 인덱스 재설정
total_data = total_data.reset_index(drop=True)
total_data

,Match_date,teamName,homeAway,Ball_Possession,Goal_Attempts,Shots_On,Shots_Off,Blocked_Shots,Free_kick,Offsides,...,Substitute_1st_Half,Substitute_2nd_Half,Throw_Ins_1st_Half,Throw_Ins_2nd_Half,Treatment_1st_Half,Treatment_2nd_Half,Yellow_Cards_1st_Half,Yellow_Cards_2nd_Half,Result,Shots_1st_Half
0,Match date: 05-08-2022 / 22:00,CRYSTAL PALACE,1,56,10,2,2,6,13,1,...,0,4,12,10,0,1,0,1.0,L,1
1,Match date: 05-08-2022 / 22:00,ARSENAL,0,44,11,2,4,5,17,2,...,0,3,12,1,0,0,1,1.0,W,3
2,Match date: 06-08-2022 / 14:30,FULHAM,1,33,9,3,2,4,13,4,...,0,3,8,13,0,0,1,NaN,D,2
3,Match date: 06-08-2022 / 14:30,LIVERPOOL,0,67,11,3,5,3,11,4,...,0,4,14,20,1,1,0,NaN,D,2
4,Match date: 06-08-2022 / 17:00,TOTTENHAM,1,57,18,8,5,5,6,2,...,0,5,12,6,0,0,1,2.0,W,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Match date: 06-05-2023 / 17:00,ASTON VILLA,0,62,17,3,6,8,23,2,...,0,5,14,6,1,3,1,2.0,L,4
526,Match date: 06-05-2023 / 17:00,TOTTENHAM,1,57,8,3,3,2,14,1,...,0,3,5,7,0,2,0,3.0,W,3
527,Match date: 06-05-2023 / 17:00,CRYSTAL PALACE,0,43,7,2,3,2,16,0,...,0,2,7,20,0,0,0,5.0,L,2
528,Match date: 06-05-2023 / 17:00,MANCHESTER CITY,1,81,18,6,10,2,19,4,...,0,3,5,7,0,1,0,0.0,W,10
529,Match date: 06-05-2023 / 17:00,LEEDS,0,19,4,2,1,1,7,3,...,0,5,4,6,0,0,1,2.0,L,2

In [8]:
# 독립변수와 종속변수 추출
total_data = total_data[['homeAway', 'Ball_Possession_1st_Half', 'Corners_1st_Half', 'Fouls_Commited_1st_Half', 'Goals_1st_Half', 'Red_Cards_1st_Half', 'Shots_1st_Half', 'Shots_On_1st_Half', 'Yellow_Cards_1st_Half', 'Result']]
total_data

,homeAway,Ball_Possession_1st_Half,Corners_1st_Half,Fouls_Commited_1st_Half,Goals_1st_Half,Red_Cards_1st_Half,Shots_1st_Half,Shots_On_1st_Half,Yellow_Cards_1st_Half,Result
0,1,45,1,8,0,0,1,1,0,L
1,0,55,2,5,1,0,3,2,1,W
2,1,29,3,5,1,0,2,1,1,D
3,0,71,1,4,0,0,2,0,0,D
4,1,58,6,7,2,0,7,5,1,W
...,...,...,...,...,...,...,...,...,...,...
525,0,60,2,3,0,0,4,3,1,L
526,1,58,4,7,1,0,3,1,0,W
527,0,42,2,2,0,0,2,1,0,L
528,1,84,3,2,2,0,10,4,0,W
529,0,16,1,6,0,0,2,1,1,L

In [9]:
#무, 패 데이터 추출
idx = total_data[total_data['Result'] == "W"].index
total_data.drop(idx, inplace = True)
total_data

C:\Users\bomul\AppData\Local\Temp\ipykernel_21680\3403987741.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_data.drop(idx, inplace = True)

,homeAway,Ball_Possession_1st_Half,Corners_1st_Half,Fouls_Commited_1st_Half,Goals_1st_Half,Red_Cards_1st_Half,Shots_1st_Half,Shots_On_1st_Half,Yellow_Cards_1st_Half,Result
0,1,45,1,8,0,0,1,1,0,L
2,1,29,3,5,1,0,2,1,1,D
3,0,71,1,4,0,0,2,0,0,D
5,0,42,1,3,1,0,3,1,0,L
7,0,36,0,8,0,0,1,0,2,L
...,...,...,...,...,...,...,...,...,...,...
521,0,34,3,5,0,0,4,2,0,L
523,0,43,5,7,0,0,8,3,1,L
525,0,60,2,3,0,0,4,3,1,L
527,0,42,2,2,0,0,2,1,0,L
529,0,16,1,6,0,0,2,1,1,L

In [10]:
# 무승부는 1로, 패배는 0으로 값 변경
total_data = total_data.replace({'Result': 'D'}, 1)
total_data = total_data.replace({'Result': 'L'}, 0)
total_data

,homeAway,Ball_Possession_1st_Half,Corners_1st_Half,Fouls_Commited_1st_Half,Goals_1st_Half,Red_Cards_1st_Half,Shots_1st_Half,Shots_On_1st_Half,Yellow_Cards_1st_Half,Result
0,1,45,1,8,0,0,1,1,0,0
2,1,29,3,5,1,0,2,1,1,1
3,0,71,1,4,0,0,2,0,0,1
5,0,42,1,3,1,0,3,1,0,0
7,0,36,0,8,0,0,1,0,2,0
...,...,...,...,...,...,...,...,...,...,...
521,0,34,3,5,0,0,4,2,0,0
523,0,43,5,7,0,0,8,3,1,0
525,0,60,2,3,0,0,4,3,1,0
527,0,42,2,2,0,0,2,1,0,0
529,0,16,1,6,0,0,2,1,1,0

In [11]:
#결측치 확인
total_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 323 entries, 0 to 529
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   homeAway                  323 non-null    int64
 1   Ball_Possession_1st_Half  323 non-null    int64
 2   Corners_1st_Half          323 non-null    int64
 3   Fouls_Commited_1st_Half   323 non-null    int64
 4   Goals_1st_Half            323 non-null    int64
 5   Red_Cards_1st_Half        323 non-null    int64
 6   Shots_1st_Half            323 non-null    int64
 7   Shots_On_1st_Half         323 non-null    int64
 8   Yellow_Cards_1st_Half     323 non-null    int64
 9   Result                    323 non-null    int64
dtypes: int64(10)
memory usage: 27.8 KB

In [12]:
#데이터 내보내기
total_data.to_csv('soccer_data.csv', index = False)

In [13]:
#타겟 데이터 따로 저장
target = total_data['Result']
#total_data에서 종속 변수 제거
total_data = total_data.drop(columns=['Result'], axis = 1)

In [14]:
total_data.head()

,homeAway,Ball_Possession_1st_Half,Corners_1st_Half,Fouls_Commited_1st_Half,Goals_1st_Half,Red_Cards_1st_Half,Shots_1st_Half,Shots_On_1st_Half,Yellow_Cards_1st_Half
0,1,45,1,8,0,0,1,1,0
2,1,29,3,5,1,0,2,1,1
3,0,71,1,4,0,0,2,0,0
5,0,42,1,3,1,0,3,1,0
7,0,36,0,8,0,0,1,0,2

In [15]:
total_data.columns

Index(['homeAway', 'Ball_Possession_1st_Half', 'Corners_1st_Half',
       'Fouls_Commited_1st_Half', 'Goals_1st_Half', 'Red_Cards_1st_Half',
       'Shots_1st_Half', 'Shots_On_1st_Half', 'Yellow_Cards_1st_Half'],
      dtype='object')

In [16]:
total_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 323 entries, 0 to 529
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   homeAway                  323 non-null    int64
 1   Ball_Possession_1st_Half  323 non-null    int64
 2   Corners_1st_Half          323 non-null    int64
 3   Fouls_Commited_1st_Half   323 non-null    int64
 4   Goals_1st_Half            323 non-null    int64
 5   Red_Cards_1st_Half        323 non-null    int64
 6   Shots_1st_Half            323 non-null    int64
 7   Shots_On_1st_Half         323 non-null    int64
 8   Yellow_Cards_1st_Half     323 non-null    int64
dtypes: int64(9)
memory usage: 25.2 KB

In [17]:
#표준화 작업
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
soccer_half_scaled = scaler.fit_transform(total_data)

In [18]:
print(soccer_half_scaled[0])

[ 1.13612506 -0.1209693  -0.61820012  1.31269469 -0.62349265 -0.12539247
 -1.16255817 -0.51072971 -0.9228321 ]

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [20]:
# X, Y 설정
Y = target
X = soccer_half_scaled

In [21]:
# 훈련 데이터와 테스트 데이터 분리
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.4, random_state = 0, stratify = Y)

In [22]:
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(193, 9) (130, 9) (193,) (130,)

In [23]:
#target 자료형 확인
Y_train.info()

<class 'pandas.core.series.Series'>
Index: 193 entries, 509 to 486
Series name: Result
Non-Null Count  Dtype
--------------  -----
193 non-null    int64
dtypes: int64(1)
memory usage: 3.0 KB

In [24]:
Y_test.info()

<class 'pandas.core.series.Series'>
Index: 130 entries, 387 to 127
Series name: Result
Non-Null Count  Dtype
--------------  -----
130 non-null    int64
dtypes: int64(1)
memory usage: 2.0 KB

In [25]:
print(round(sum(Y_train)/len(Y_train)*100, 2), '%')

35.75 %

In [26]:
print(round(sum(Y_test)/len(Y_test)*100, 2), '%')

36.15 %

In [27]:
lr_soccer_half = LogisticRegression(max_iter=10000) #max_iter 확인
lr_soccer_half.fit(X_train, Y_train)

LogisticRegression(max_iter=10000)

In [28]:
Y_predict = lr_soccer_half.predict(X_test)

In [29]:
lr_soccer_half.coef_

array([[ 0.36845947,  0.33079737, -0.00538451, -0.047014  ,  0.3588101 ,
        -0.42056259,  0.33831404, -0.08964678,  0.31067116]])

In [30]:
lr_soccer_half.intercept_

array([-0.71330266])

로지스틱 회귀모형 평가

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [32]:
# 오차행렬 확인 (예측치와 실제값 비교)
confusion_matrix(Y_test, Y_predict)

array([[74,  9],
       [37, 10]], dtype=int64)

In [33]:
accuracy = accuracy_score(Y_test, Y_predict)
precision = precision_score(Y_test, Y_predict)
recall = recall_score(Y_test, Y_predict)
f1 = f1_score(Y_test, Y_predict)

In [34]:
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}, F1: {3:.3f}'.format(accuracy, precision, recall, f1))

정확도: 0.646, 정밀도: 0.526, 재현율: 0.213, F1: 0.303

In [35]:
import statsmodels.api as sm

In [36]:
logit_m = sm.Logit(Y_train, X_train)
logit_m_train = logit_m.fit(method='powell')

Optimization terminated successfully.
         Current function value: 0.619509
         Iterations: 4
         Function evaluations: 367

In [37]:
logit_m_train.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 Result   No. Observations:                  193
Model:                          Logit   Df Residuals:                      184
Method:                           MLE   Df Model:                            8
Date:                Wed, 24 May 2023   Pseudo R-squ.:                 0.04979
Time:                        00:19:50   Log-Likelihood:                -119.57
converged:                       True   LL-Null:                       -125.83
Covariance Type:            nonrobust   LLR p-value:                    0.1290
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.3265      0.163      2.008      0.045       0.008       0.645
x2             0.3585      0.173      2.074      0.038       0.020       0.697
x3            -0.0431      0.176     -0.246      0.806      -0.388       0.301
x4            -0.0727      0.165     -0.442      0.659      -0.395       0.250
x5             0.3745      0.187      2.006      0.045       0.009       0.740
x6            -0.2239      0.212     -1.054      0.292      -0.640       0.192
x7             0.3210      0.262      1.226      0.220      -0.192       0.834
x8            -0.1027      0.261     -0.394      0.694      -0.614       0.409
x9             0.2767      0.167      1.660      0.097      -0.050       0.603
==============================================================================
"""